// Curated entity->listing seed map — DATA ONLY, no logic. This is the file to edit when a
// mapping goes stale (M&A, delisting, new listing). Keys are normalizeName() output
// (lowercase, legal suffixes stripped). status: "public" | "private" | "subsidiary".
// Private entries carry relatedTickers (listed companies with material economic exposure)
// plus a one-line English note; subsidiaries point at their listed parent.

export const SEED_MAP = {
  // --- US mega caps / AI platforms ---
  "nvidia": { displayName: "NVIDIA", status: "public", ticker: "NVDA", exchange: "NasdaqGS", aliases: ["nvidia"], sizeHint: "large" },
  "microsoft": { displayName: "Microsoft", status: "public", ticker: "MSFT", exchange: "NasdaqGS", aliases: ["microsoft"], sizeHint: "large" },
  "apple": { displayName: "Apple", status: "public", ticker: "AAPL", exchange: "NasdaqGS", aliases: ["apple"], sizeHint: "large" },
  "alphabet": { displayName: "Alphabet", status: "public", ticker: "GOOGL", exchange: "NasdaqGS", aliases: ["alphabet", "google"], sizeHint: "large" },
  "google": { displayName: "Google", status: "subsidiary", ticker: "GOOGL", exchange: "NasdaqGS", parent: "Alphabet", aliases: ["google"], sizeHint: "large" },
  "amazon": { displayName: "Amazon", status: "public", ticker: "AMZN", exchange: "NasdaqGS", aliases: ["amazon"], sizeHint: "large" },
  "meta": { displayName: "Meta Platforms", status: "public", ticker: "META", exchange: "NasdaqGS", aliases: ["meta platforms", "meta"], sizeHint: "large" },
  "tesla": { displayName: "Tesla", status: "public", ticker: "TSLA", exchange: "NasdaqGS", aliases: ["tesla"], sizeHint: "large" },
  "netflix": { displayName: "Netflix", status: "public", ticker: "NFLX", exchange: "NasdaqGS", aliases: ["netflix"], sizeHint: "large" },
  "oracle": { displayName: "Oracle", status: "public", ticker: "ORCL", exchange: "NYSE", aliases: ["oracle"], sizeHint: "large" },
  "ibm": { displayName: "IBM", status: "public", ticker: "IBM", exchange: "NYSE", aliases: ["ibm"], sizeHint: "large" },
  "salesforce": { displayName: "Salesforce", status: "public", ticker: "CRM", exchange: "NYSE", aliases: ["salesforce"], sizeHint: "large" },
  "adobe": { displayName: "Adobe", status: "public", ticker: "ADBE", exchange: "NasdaqGS", aliases: ["adobe"], sizeHint: "large" },
  "palantir": { displayName: "Palantir", status: "public", ticker: "PLTR", exchange: "NasdaqGS", aliases: ["palantir"], sizeHint: "large" },
  "servicenow": { displayName: "ServiceNow", status: "public", ticker: "NOW", exchange: "NYSE", aliases: ["servicenow"], sizeHint: "large" },
  "snowflake": { displayName: "Snowflake", status: "public", ticker: "SNOW", exchange: "NYSE", aliases: ["snowflake"], sizeHint: "mid" },
  "uber": { displayName: "Uber", status: "public", ticker: "UBER", exchange: "NYSE", aliases: ["uber"], sizeHint: "large" },

  // --- Semiconductors / AI hardware ---
  "amd": { displayName: "AMD", status: "public", ticker: "AMD", exchange: "NasdaqGS", aliases: ["amd", "advanced micro devices"], sizeHint: "large" },
  "advanced micro devices": { displayName: "AMD", status: "public", ticker: "AMD", exchange: "NasdaqGS", aliases: ["amd", "advanced micro devices"], sizeHint: "large" },
  "intel": { displayName: "Intel", status: "public", ticker: "INTC", exchange: "NasdaqGS", aliases: ["intel"], sizeHint: "large" },
  "qualcomm": { displayName: "Qualcomm", status: "public", ticker: "QCOM", exchange: "NasdaqGS", aliases: ["qualcomm"], sizeHint: "large" },
  "broadcom": { displayName: "Broadcom", status: "public", ticker: "AVGO", exchange: "NasdaqGS", aliases: ["broadcom"], sizeHint: "large" },
  "tsmc": { displayName: "TSMC", status: "public", ticker: "TSM", exchange: "NYSE", aliases: ["tsmc", "taiwan semiconductor"], sizeHint: "large", note: "US ADR; home listing Taipei" },
  "taiwan semiconductor": { displayName: "TSMC", status: "public", ticker: "TSM", exchange: "NYSE", aliases: ["tsmc", "taiwan semiconductor"], sizeHint: "large" },
  "micron": { displayName: "Micron", status: "public", ticker: "MU", exchange: "NasdaqGS", aliases: ["micron"], sizeHint: "large" },
  "arm": { displayName: "Arm Holdings", status: "public", ticker: "ARM", exchange: "NasdaqGS", aliases: ["arm holdings"], sizeHint: "large", note: "Alias deliberately two words — \"arm\" alone is too ambiguous" },
  "asml": { displayName: "ASML", status: "public", ticker: "ASML", exchange: "NasdaqGS", aliases: ["asml"], sizeHint: "large", note: "US listing; home listing Amsterdam ASML.AS" },
  "super micro computer": { displayName: "Super Micro Computer", status: "public", ticker: "SMCI", exchange: "NasdaqGS", aliases: ["super micro computer", "supermicro"], sizeHint: "mid" },
  "dell": { displayName: "Dell Technologies", status: "public", ticker: "DELL", exchange: "NYSE", aliases: ["dell"], sizeHint: "large" },

  // --- German / European tech + industry (XETRA primary per preferXetra) ---
  "sap": { displayName: "SAP", status: "public", ticker: "SAP.DE", exchange: "XETRA", aliases: ["sap"], sizeHint: "large" },
  "siemens": { displayName: "Siemens", status: "public", ticker: "SIE.DE", exchange: "XETRA", aliases: ["siemens"], sizeHint: "large" },
  "siemens energy": { displayName: "Siemens Energy", status: "public", ticker: "ENR.DE", exchange: "XETRA", aliases: ["siemens energy"], sizeHint: "large" },
  "siemens healthineers": { displayName: "Siemens Healthineers", status: "public", ticker: "SHL.DE", exchange: "XETRA", aliases: ["siemens healthineers", "healthineers"], sizeHint: "large" },
  "infineon": { displayName: "Infineon", status: "public", ticker: "IFX.DE", exchange: "XETRA", aliases: ["infineon"], sizeHint: "large" },
  "deutsche telekom": { displayName: "Deutsche Telekom", status: "public", ticker: "DTE.DE", exchange: "XETRA", aliases: ["deutsche telekom", "telekom"], sizeHint: "large" },
  "deutsche bank": { displayName: "Deutsche Bank", status: "public", ticker: "DBK.DE", exchange: "XETRA", aliases: ["deutsche bank"], sizeHint: "large" },
  "deutsche boerse": { displayName: "Deutsche Börse", status: "public", ticker: "DB1.DE", exchange: "XETRA", aliases: ["deutsche börse", "deutsche boerse"], sizeHint: "large" },
  "allianz": { displayName: "Allianz", status: "public", ticker: "ALV.DE", exchange: "XETRA", aliases: ["allianz"], sizeHint: "large" },
  "volkswagen": { displayName: "Volkswagen", status: "public", ticker: "VOW3.DE", exchange: "XETRA", aliases: ["volkswagen"], sizeHint: "large" },
  "bmw": { displayName: "BMW", status: "public", ticker: "BMW.DE", exchange: "XETRA", aliases: ["bmw"], sizeHint: "large" },
  "mercedes-benz": { displayName: "Mercedes-Benz", status: "public", ticker: "MBG.DE", exchange: "XETRA", aliases: ["mercedes-benz", "mercedes"], sizeHint: "large" },
  "bosch": { displayName: "Bosch", status: "private", ticker: null, aliases: ["bosch"], relatedTickers: [], note: "Foundation-owned, not publicly listed" },
  "zeiss": { displayName: "Carl Zeiss", status: "private", ticker: null, aliases: ["zeiss", "carl zeiss"], relatedTickers: ["AFX.DE"], note: "Group is foundation-owned; Carl Zeiss Meditec (AFX.DE) is listed" },
  "carl zeiss meditec": { displayName: "Carl Zeiss Meditec", status: "public", ticker: "AFX.DE", exchange: "XETRA", aliases: ["carl zeiss meditec"], sizeHint: "mid" },
  "rheinmetall": { displayName: "Rheinmetall", status: "public", ticker: "RHM.DE", exchange: "XETRA", aliases: ["rheinmetall"], sizeHint: "large" },
  "airbus": { displayName: "Airbus", status: "public", ticker: "AIR.DE", exchange: "XETRA", aliases: ["airbus"], sizeHint: "large" },
  "bayer": { displayName: "Bayer", status: "public", ticker: "BAYN.DE", exchange: "XETRA", aliases: ["bayer"], sizeHint: "large" },
  "basf": { displayName: "BASF", status: "public", ticker: "BAS.DE", exchange: "XETRA", aliases: ["basf"], sizeHint: "large" },
  "merck kgaa": { displayName: "Merck KGaA (Darmstadt)", status: "public", ticker: "MRK.DE", exchange: "XETRA", aliases: ["merck kgaa"], sizeHint: "large", note: "NOT Merck & Co (US, MRK) — a classic mix-up" },
  "zalando": { displayName: "Zalando", status: "public", ticker: "ZAL.DE", exchange: "XETRA", aliases: ["zalando"], sizeHint: "mid" },
  "delivery hero": { displayName: "Delivery Hero", status: "public", ticker: "DHER.DE", exchange: "XETRA", aliases: ["delivery hero"], sizeHint: "mid" },
  "hellofresh": { displayName: "HelloFresh", status: "public", ticker: "HFG.DE", exchange: "XETRA", aliases: ["hellofresh"], sizeHint: "mid" },
  "teamviewer": { displayName: "TeamViewer", status: "public", ticker: "TMV.DE", exchange: "XETRA", aliases: ["teamviewer"], sizeHint: "mid" },
  "nemetschek": { displayName: "Nemetschek", status: "public", ticker: "NEM.DE", exchange: "XETRA", aliases: ["nemetschek"], sizeHint: "mid" },
  "aixtron": { displayName: "AIXTRON", status: "public", ticker: "AIXA.DE", exchange: "XETRA", aliases: ["aixtron"], sizeHint: "mid" },
  "suess microtec": { displayName: "SÜSS MicroTec", status: "public", ticker: "SMHN.DE", exchange: "XETRA", aliases: ["süss microtec", "suess microtec"], sizeHint: "small" },
  "jenoptik": { displayName: "Jenoptik", status: "public", ticker: "JEN.DE", exchange: "XETRA", aliases: ["jenoptik"], sizeHint: "small" },
  "kontron": { displayName: "Kontron", status: "public", ticker: "SANT.DE", exchange: "XETRA", aliases: ["kontron"], sizeHint: "small" },
  "adesso": { displayName: "adesso", status: "public", ticker: "ADN1.DE", exchange: "XETRA", aliases: ["adesso"], sizeHint: "small" },
  "cancom": { displayName: "CANCOM", status: "public", ticker: "COK.DE", exchange: "XETRA", aliases: ["cancom"], sizeHint: "small" },
  "bechtle": { displayName: "Bechtle", status: "public", ticker: "BC8.DE", exchange: "XETRA", aliases: ["bechtle"], sizeHint: "mid" },
  "ionos": { displayName: "IONOS", status: "public", ticker: "IOS.DE", exchange: "XETRA", aliases: ["ionos"], sizeHint: "small" },
  "united internet": { displayName: "United Internet", status: "public", ticker: "UTDI.DE", exchange: "XETRA", aliases: ["united internet"], sizeHint: "mid" },
  "schwarz gruppe": { displayName: "Schwarz Gruppe", status: "private", ticker: null, aliases: ["schwarz gruppe", "schwarz digits"], relatedTickers: [], note: "Lidl/Kaufland parent with AI-cloud ambitions (Schwarz Digits), not listed" },
  "asml holding": { displayName: "ASML", status: "public", ticker: "ASML", exchange: "NasdaqGS", aliases: ["asml"], sizeHint: "large" },
  "stmicroelectronics": { displayName: "STMicroelectronics", status: "public", ticker: "STM", exchange: "NYSE", aliases: ["stmicroelectronics"], sizeHint: "large" },
  "nokia": { displayName: "Nokia", status: "public", ticker: "NOK", exchange: "NYSE", aliases: ["nokia"], sizeHint: "large" },
  "ericsson": { displayName: "Ericsson", status: "public", ticker: "ERIC", exchange: "NasdaqGS", aliases: ["ericsson"], sizeHint: "large" },
  "spotify": { displayName: "Spotify", status: "public", ticker: "SPOT", exchange: "NYSE", aliases: ["spotify"], sizeHint: "large" },

  // --- AI labs & startups (private — relatedTickers = listed exposure) ---
  "openai": { displayName: "OpenAI", status: "private", ticker: null, aliases: ["openai", "open ai"], relatedTickers: ["MSFT", "NVDA"], note: "Microsoft stake, NVIDIA compute — indirect exposure" },
  "anthropic": { displayName: "Anthropic", status: "private", ticker: null, aliases: ["anthropic"], relatedTickers: ["GOOGL", "AMZN"], note: "Google and Amazon stakes" },
  "mistral": { displayName: "Mistral AI", status: "private", ticker: null, aliases: ["mistral ai", "mistral"], relatedTickers: ["NVDA"], note: "French AI lab, VC-funded" },
  "mistral ai": { displayName: "Mistral AI", status: "private", ticker: null, aliases: ["mistral ai", "mistral"], relatedTickers: ["NVDA"], note: "French AI lab, VC-funded" },
  "aleph alpha": { displayName: "Aleph Alpha", status: "private", ticker: null, aliases: ["aleph alpha"], relatedTickers: [], note: "Heidelberg AI company; investors include Schwarz Gruppe (private), SAP" },
  "xai": { displayName: "xAI", status: "private", ticker: null, aliases: ["xai"], relatedTickers: ["TSLA", "NVDA"], note: "Musk ecosystem; Tesla/NVIDIA as listed proxies" },
  "deepseek": { displayName: "DeepSeek", status: "private", ticker: null, aliases: ["deepseek"], relatedTickers: [], note: "Chinese AI lab (High-Flyer fund), not listed" },
  "black forest labs": { displayName: "Black Forest Labs", status: "private", ticker: null, aliases: ["black forest labs"], relatedTickers: [], note: "German image-model startup (FLUX), VC-funded" },
  "hugging face": { displayName: "Hugging Face", status: "private", ticker: null, aliases: ["hugging face", "huggingface"], relatedTickers: ["AMZN", "GOOGL", "NVDA"], note: "Platform; investors include Amazon/Google/NVIDIA" },
  "perplexity": { displayName: "Perplexity", status: "private", ticker: null, aliases: ["perplexity"], relatedTickers: ["NVDA"], note: "AI search, VC-funded" },
  "stability ai": { displayName: "Stability AI", status: "private", ticker: null, aliases: ["stability ai"], relatedTickers: [], note: "Image models, VC-funded" },
  "cohere": { displayName: "Cohere", status: "private", ticker: null, aliases: ["cohere"], relatedTickers: ["ORCL", "NVDA"], note: "Enterprise LLMs; Oracle partnership" },
  "databricks": { displayName: "Databricks", status: "private", ticker: null, aliases: ["databricks"], relatedTickers: ["NVDA", "MSFT"], note: "Data/AI platform, IPO candidate" },
  "figure": { displayName: "Figure AI", status: "private", ticker: null, aliases: ["figure ai"], relatedTickers: ["NVDA", "MSFT"], note: "Humanoid robotics; alias deliberately two words" },
  "waymo": { displayName: "Waymo", status: "subsidiary", ticker: "GOOGL", exchange: "NasdaqGS", parent: "Alphabet", aliases: ["waymo"], note: "Alphabet subsidiary" },

  // --- Subsidiaries / brands -> listed parent ---
  "youtube": { displayName: "YouTube", status: "subsidiary", ticker: "GOOGL", exchange: "NasdaqGS", parent: "Alphabet", aliases: ["youtube"] },
  "deepmind": { displayName: "Google DeepMind", status: "subsidiary", ticker: "GOOGL", exchange: "NasdaqGS", parent: "Alphabet", aliases: ["deepmind", "google deepmind"] },
  "github": { displayName: "GitHub", status: "subsidiary", ticker: "MSFT", exchange: "NasdaqGS", parent: "Microsoft", aliases: ["github"] },
  "linkedin": { displayName: "LinkedIn", status: "subsidiary", ticker: "MSFT", exchange: "NasdaqGS", parent: "Microsoft", aliases: ["linkedin"] },
  "aws": { displayName: "AWS", status: "subsidiary", ticker: "AMZN", exchange: "NasdaqGS", parent: "Amazon", aliases: ["aws", "amazon web services"] },
  "instagram": { displayName: "Instagram", status: "subsidiary", ticker: "META", exchange: "NasdaqGS", parent: "Meta Platforms", aliases: ["instagram"] },
  "whatsapp": { displayName: "WhatsApp", status: "subsidiary", ticker: "META", exchange: "NasdaqGS", parent: "Meta Platforms", aliases: ["whatsapp"] },
  "azure": { displayName: "Microsoft Azure", status: "subsidiary", ticker: "MSFT", exchange: "NasdaqGS", parent: "Microsoft", aliases: ["azure"] },
  "chatgpt": { displayName: "ChatGPT", status: "private", ticker: null, aliases: ["chatgpt"], relatedTickers: ["MSFT", "NVDA"], note: "OpenAI product — exposure like OpenAI" },
  "claude": { displayName: "Claude", status: "private", ticker: null, aliases: [], relatedTickers: ["GOOGL", "AMZN"], note: "Anthropic product; no alias — \"claude\" is too ambiguous as a word" },
  "gemini": { displayName: "Google Gemini", status: "subsidiary", ticker: "GOOGL", exchange: "NasdaqGS", parent: "Alphabet", aliases: [], note: "No alias — Gemini is ambiguous (crypto exchange, etc.)" }
};
